[platformio]
default_envs = nano_esp32_release

[env]
platform = espressif32@6.7.0
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
  lvgl/lvgl@9.1.0
  mikalhart/TinyGPSPlus@1.0.3
build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CCM_CAN_BITRATE=500000
  -D CCM_CAN_PROTOCOL_VERSION=1

[env:nano_esp32_debug]
board = arduino_nano_esp32
build_type = debug
build_flags =
  ${env.build_flags}
  -D CCM_BUILD_DEBUG=1

[env:nano_esp32_release]
board = arduino_nano_esp32
build_type = release
build_flags =
  ${env.build_flags}
  -D CCM_BUILD_DEBUG=0
