[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DCCM_CAN_PROTOCOL_VERSION=1
  -I ../../shared/can_contract/include
