[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
lib_deps =
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0
  https://github.com/coryjfowler/MCP_CAN_lib
build_src_filter = +<*> -<can_bridge.cpp>
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DCCM_CAN_PROTOCOL_VERSION=1
  -I ../../shared/can_contract/include
